"""
agents/app_agent.py — JARVIS App Development Agent (Enhanced).

Specialist for: desktop apps, mobile apps, installers, packaging,
cross-platform development, GUI apps, CLI tools.
Now with real project creation and file generation.
"""

from __future__ import annotations

import logging
import os
import time
from pathlib import Path
from typing import Any

logger = logging.getLogger("jarvis.agent.app")

_BASE = Path(__file__).resolve().parent.parent


def _llm(prompt: str, system: str | None = None, timeout: int = 120) -> str:
    try:
        from core.llm_client import call_llm_text
        return call_llm_text(prompt, system=system, timeout=timeout)
    except Exception:
        from core.gemini_text import generate
        return generate(prompt, system=system, timeout=timeout)


def execute(task: str, context: str = "", workspace: str | None = None) -> dict[str, Any]:
    """Execute an app development task."""
    start = time.time()
    ws = Path(workspace) if workspace else _BASE

    # Phase 1: Plan the app
    plan = _plan_app(task, context)
    if not plan["success"]:
        return {
            "agent": "app",
            "status": "error",
            "result": plan["error"],
            "created_files": [],
            "elapsed_seconds": round(time.time() - start, 1),
            "summary": "Failed to plan app.",
        }

    # Phase 2: Build the app
    build_result = _build_app(plan["plan"], task, ws)
    elapsed = time.time() - start

    return {
        "agent": "app",
        "status": "success" if build_result["success"] else "error",
        "result": build_result["message"],
        "created_files": build_result.get("files", []),
        "project_path": build_result.get("project_path"),
        "elapsed_seconds": round(elapsed, 1),
        "summary": build_result.get("summary", "App build complete."),
    }


def _plan_app(task: str, context: str) -> dict[str, Any]:
    """Plan the app structure."""
    system = (
        "You are an app architect. Given a task, output a JSON plan for the app. "
        "The JSON must have this exact format:\n"
        '{"type": "desktop" | "mobile" | "web" | "cli", '
        '"framework": "tkinter" | "pyqt" | "electron" | "flutter" | "fastapi" | "streamlit", '
        '"language": "python" | "javascript" | "typescript", '
        '"files": [{"name": "main.py", "purpose": "entry point"}], '
        '"features": ["feature1", "feature2"]}\n'
        "Be concise. Return ONLY valid JSON, no markdown, no explanation."
    )
    prompt = f"TASK: {task}\nCONTEXT: {context}\n\nOutput the app plan as JSON."

    try:
        raw = _llm(prompt, system=system, timeout=60)
        raw = raw.strip()
        if raw.startswith("```"):
            raw = raw.split("\n", 1)[1].rsplit("```", 1)[0]
        start, end = raw.find("{"), raw.rfind("}")
        if start == -1 or end == -1:
            return {"success": False, "error": "LLM did not return valid JSON plan."}
        plan = json.loads(raw[start:end + 1])
        return {"success": True, "plan": plan}
    except Exception as e:
        return {"success": False, "error": f"Planning failed: {e}"}


def _build_app(plan: dict, task: str, ws: Path) -> dict[str, Any]:
    """Build the actual app files."""
    try:
        # Create project directory
        project_name = f"app_{int(time.time())}"
        project_dir = ws / "app_output" / project_name
        project_dir.mkdir(parents=True, exist_ok=True)

        system = (
            "You are an expert app developer. Generate complete, runnable code for ALL files in the project. "
            "For each file, output it in a separate code block with the filename as a comment. "
            "Make the code production-ready with error handling and comments. "
            "Format: # filename: path/to/file.ext followed by the code."
        )
        prompt = f"TASK: {task}\nPLAN: {json.dumps(plan)}\n\nGenerate all project files."

        result = _llm(prompt, system=system, timeout=180)

        # Parse and save files
        saved_files = _parse_and_save_files(result, project_dir)

        if not saved_files:
            # Fallback: create a simple main file
            main_file = project_dir / "main.py"
            main_file.write_text(f'#!/usr/bin/env python3\n"""Auto-generated by JARVIS App Agent."""\n\n\ndef main():\n    print("App by JARVIS\\nTask: {task[:100]}")\n\n\nif __name__ == "__main__":\n    main()\n', encoding="utf-8")
            saved_files.append(str(main_file))

        # Create README
        readme = project_dir / "README.md"
        readme.write_text(
            f"# {task[:50]}\n\nGenerated by JARVIS App Agent.\n\n"
            f"## Files\n" + "\n".join(f"- {Path(f).name}" for f in saved_files) + "\n\n"
            f"## How to Run\nSee individual files for instructions.\n",
            encoding="utf-8"
        )

        return {
            "success": True,
            "message": f"App project created with {len(saved_files)} file(s).",
            "files": saved_files,
            "project_path": str(project_dir),
            "summary": f"Built {plan.get('type', 'app')} app with {len(saved_files)} file(s) using {plan.get('framework', 'custom')}.",
        }
    except Exception as e:
        logger.error("App build failed: %s", e)
        return {"success": False, "message": f"Build failed: {e}", "files": []}


def _parse_and_save_files(result: str, project_dir: Path) -> list[str]:
    """Parse LLM output and save individual files."""
    import re
    saved = []
    try:
        # Look for file blocks: # filename: path/to/file.ext
        pattern = r'#\s*filename[:\s]+([^\n]+)\n(.*?)(?=#\s*filename|\Z)'
        matches = re.findall(pattern, result, re.DOTALL)

        if not matches:
            # Try code blocks
            pattern2 = r'```(?:python|py|javascript|js|typescript|ts|java|cpp|c|html|css|json|yaml|bash)\n(.*?)```'
            code_blocks = re.findall(pattern2, result, re.DOTALL)
            if code_blocks:
                main_file = project_dir / "main.py"
                main_file.write_text(code_blocks[0].strip(), encoding="utf-8")
                saved.append(str(main_file))
            return saved

        for fname, content in matches[:10]:
            fname = fname.strip().strip('"').strip("'")
            if not fname:
                continue
            fpath = project_dir / fname
            fpath.parent.mkdir(parents=True, exist_ok=True)
            content = content.strip()
            if content.startswith("```"):
                content = content.split("\n", 1)[1].rsplit("```", 1)[0]
            fpath.write_text(content.strip(), encoding="utf-8")
            saved.append(str(fpath))
    except Exception as e:
        logger.debug("Failed to parse files: %s", e)
    return saved


def _extract_summary(result: str) -> str:
    if not result:
        return "No output generated."
    lines = result.strip().splitlines()
    for line in lines:
        line = line.strip()
        if line and len(line) > 10 and not line.startswith("#") and not line.startswith("```"):
            return line[:120]
    return lines[0][:120] if lines else "Task completed."
